### ISSUE TITLE
create new issue

### ISSUE THREAD

**Issue by carepack** [berti92/mega_calendar#40] opened 2016-10-05 09:40 UTC
hi,

I have configured my redmine installation to a sub path:
www.website.xyz/redmine
The subpath is also defined in the plugin settings. The only thing which is not working is creating a new issue. Calendar plugin is usin the path without the subpath:
www.website.xyz/tickets_issue_****
If I enter the subpath manually it works very well.

**Comment by berti92** [comment] 2016-10-05 15:29
I'm sorry I can't reproduce your problem. Did you set "/redmine" as sub-path?

**Comment by carepack** [comment] 2016-10-05 16:30
Yep, the subpath is configured in the mega_calendar settings. It's only happening when a issue is going to be created out of the calendar. Everything else is working fine.

**Comment by berti92** [comment] 2016-10-05 16:42
Ahhhhhhh now i understand, it should be fixed now :)

**Closed** 2016-10-05 16:42 UTC

**Comment by carepack** [comment] 2016-10-06 07:26
ok, the link iscorrect now, but folowing error is produced and I can't determine if it's a mega calendar problem or not:
`Redmine. Error 500

Global error
undefined method `module_enabled?' for nil:NilClass 

Back  

Error log

        /opt/redmine/redmine-3.3.0/plugins/scrum/app/views/scrum_hooks/issues/_form.html.erb:1:in `_plugins_scrum_app_views_scrum_hooks_issues__form_html_erb___242737821645296616_70200921800760'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:145:in `block in render'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:333:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:143:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:25:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/opt/redmine/redmine-3.3.0/lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
/opt/redmine/redmine-3.3.0/lib/redmine/hook/view_listener.rb:57:in `map'
/opt/redmine/redmine-3.3.0/lib/redmine/hook/view_listener.rb:57:in `block in render_on'
/opt/redmine/redmine-3.3.0/lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
/opt/redmine/redmine-3.3.0/lib/redmine/hook.rb:61:in `each'
/opt/redmine/redmine-3.3.0/lib/redmine/hook.rb:61:in `block in call_hook'
/opt/redmine/redmine-3.3.0/lib/redmine/hook.rb:58:in `tap'
/opt/redmine/redmine-3.3.0/lib/redmine/hook.rb:58:in `call_hook'
/opt/redmine/redmine-3.3.0/lib/redmine/hook.rb:96:in `call_hook'
/opt/redmine/redmine-3.3.0/plugins/mega_calendar/app/views/issues/_form.html.erb:47:in `block in _plugins_mega_calendar_app_views_issues__form_html_erb___4339245662019011514_70200920110940'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:38:in `capture'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/form_helper.rb:714:in `fields_for'
/opt/redmine/redmine-3.3.0/app/helpers/application_helper.rb:1058:in `labelled_fields_for'
/opt/redmine/redmine-3.3.0/plugins/mega_calendar/app/views/issues/_form.html.erb:4:in `_plugins_mega_calendar_app_views_issues__form_html_erb___4339245662019011514_70200920110940'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:145:in `block in render'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:333:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:143:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:25:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/opt/redmine/redmine-3.3.0/app/views/issues/new.html.erb:11:in `block in _app_views_issues_new_html_erb___4004947420342873927_70200919975220'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb:38:in `capture'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/helpers/form_helper.rb:444:in `form_for'
/opt/redmine/redmine-3.3.0/app/helpers/application_helper.rb:1051:in `labelled_form_for'
/opt/redmine/redmine-3.3.0/app/views/issues/new.html.erb:5:in `_app_views_issues_new_html_erb___4004947420342873927_70200919975220'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:145:in `block in render'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:333:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/template.rb:143:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:14:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:46:in `render_template'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:27:in `render'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:100:in `_render_template'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:83:in `render_to_body'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/rendering.rb:25:in `render'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:16:in `render'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/var/lib/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:43:in `render'
/opt/redmine/redmine-3.3.0/app/controllers/issues_controller.rb:129:in `block (2 levels) in new'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/mime_responds.rb:217:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
/opt/redmine/redmine-3.3.0/app/controllers/issues_controller.rb:128:in `new'
/opt/redmine/redmine-3.3.0/plugins/usability/lib/usability/issues_controller_patch.rb:32:in `new_with_usability'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:313:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/opt/redmine/redmine-3.3.0/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:312:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:312:in `block in halting'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `block in around'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/lib/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
/var/lib/gems/2.1.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
/var/lib/gems/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/var/lib/gems/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/lib/gems/2.1.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/lib/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
/var/lib/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'`

Any ideas?

**Comment by berti92** [comment] 2016-10-06 13:56
Hmmmm looks like the the scrum and my plugin conflicts
